### PR TITLE
Cannot use RouteHelper as RouteHelper already in use in Helper\TemplateHelper.php

### PR DESCRIPTION
**Pull request by xillibit**
Fatal error: Cannot use RouteHelper as RouteHelper because the name is already in use in C:\wamp\www\cobalt-master\src\Cobalt\Helper\TemplateHelper.php on line 14

### CODE REVIEW

**Comment by escopecz** [comment]
Hi, could you describe how could we replicate this error?

**Comment by xillibit** [comment]
When it's installed, just try to login enter your username and password and then when you sumbit you have this issue

**Comment by dongilbert** [comment]
The class `Cobalt\Helper\RouteHelper` exists, so there is no need to import it in the `TemplateHelper`. It's already available.

**Comment by escopecz** [comment]
Try to update your Cobalt installation from this repo. Login/logout has been changed. Also, go to configuration.php and change

```
public $dbtype = 'mysql';
```

to

```
public $dbtype = 'mysqli';
```

**Comment by dongilbert** [comment]
Removing the line in the `TemplateHelper`, as indicated in the PR, will fix the issue of a fatal error being caused due to importing the `RouterHelper` class into a namespace in which it already exists. That's what causing the error.

**Comment by dongilbert** [comment]
This bug also effects the `MenuHelper` https://github.com/cobaltcrm/cobalt/blob/master/src/Cobalt/Helper/MenuHelper.php#L14 and `CPanelHelper` https://github.com/cobaltcrm/cobalt/blob/master/src/Cobalt/Helper/CPanelHelper.php#L13

**Comment by escopecz** [comment]
Ok, guys. Thanks for feedback, I'll merge it.

**Comment by escopecz** [comment]
I think this was caused when I replaced 

```
use JRoute;
```

with

```
use RouteHelper;
```

commit: https://github.com/cobaltcrm/cobalt/commit/cd44702bc41f3b71990181ab2f1ad1580e027357

I'll delete

```
use RouteHelper;
```

at all files from the commit.

**Comment by dongilbert** [comment]
I would not do it at all files, because it's only causing this specific fatal error when having the `use RouteHelper` statement within another helper file in the same directory.

The others should be changed to `use Cobalt\Helpers\RouteHelper` instead.

**Comment by escopecz** [comment]
Ok, done. I couldn't replicate the error you are having though...

**Comment by xillibit** [comment]
With the latest changes i don't have this error anymore :cool:

**Pull request merged**
